"""empty message

Revision ID: 07c367c22c37
Revises: 1ce3412bb5ca
Create Date: 2021-11-09 22:32:58.690332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c367c22c37'
down_revision = '1ce3412bb5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
