"""empty message

Revision ID: 11489673955e
Revises: 62e334a3972d
Create Date: 2021-11-09 22:43:20.237155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11489673955e'
down_revision = '62e334a3972d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
