"""empty message

Revision ID: 1ce3412bb5ca
Revises: 
Create Date: 2021-11-09 22:23:40.534198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce3412bb5ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('doctor_id_key', 'doctor', type_='unique')
    op.drop_column('doctor', 'id')
    op.drop_constraint('publicservant_id_key', 'publicservant', type_='unique')
    op.drop_column('publicservant', 'id')
    op.drop_column('specialize', 'doctor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialize', sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('publicservant', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('publicservant_id_key', 'publicservant', ['id'])
    op.add_column('doctor', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('doctor_id_key', 'doctor', ['id'])
    # ### end Alembic commands ###
