"""empty message

Revision ID: 77065192f23e
Revises: 96def40c5cf4
Create Date: 2021-11-10 18:42:41.416517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77065192f23e'
down_revision = '96def40c5cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discover', sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False))
    op.add_column('disease', sa.Column('dis_id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False))
    op.add_column('record', sa.Column('rec_id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False))
    op.drop_constraint('record_id_key', 'record', type_='unique')
    op.drop_column('record', 'id')
    op.add_column('specialize', sa.Column('spec_id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialize', 'spec_id')
    op.add_column('record', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('record_id_key', 'record', ['id'])
    op.drop_column('record', 'rec_id')
    op.drop_column('disease', 'dis_id')
    op.drop_column('discover', 'id')
    # ### end Alembic commands ###
