"""empty message

Revision ID: 96def40c5cf4
Revises: fd56981b780a
Create Date: 2021-11-09 23:40:40.862104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96def40c5cf4'
down_revision = 'fd56981b780a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
