"""empty message

Revision ID: 978eeff3a541
Revises: 80d760948aa1
Create Date: 2021-11-09 22:37:43.540897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978eeff3a541'
down_revision = '80d760948aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
