"""empty message

Revision ID: d790c5ed597e
Revises: dc8724a53f87
Create Date: 2021-11-17 04:41:43.690126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd790c5ed597e'
down_revision = 'dc8724a53f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discover_disease_code_fkey', 'discover', type_='foreignkey')
    op.create_foreign_key(None, 'discover', 'disease', ['disease_code'], ['disease_code'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discover', type_='foreignkey')
    op.create_foreign_key('discover_disease_code_fkey', 'discover', 'disease', ['disease_code'], ['disease_code'], ondelete='CASCADE')
    # ### end Alembic commands ###
