"""empty message

Revision ID: dc8724a53f87
Revises: 77065192f23e
Create Date: 2021-11-15 23:12:39.954214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8724a53f87'
down_revision = '77065192f23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disease', sa.Column('creator', sa.String(length=60), nullable=False))
    op.create_foreign_key(None, 'disease', 'doctor', ['creator'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disease', type_='foreignkey')
    op.drop_column('disease', 'creator')
    # ### end Alembic commands ###
